AllCops:
  Exclude:
    - Gemfile
    - db/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - app/models/role.rb
    - vendor/**/*
    - bundler_stubs/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 90
  # Ignores comment line length
  IgnoredPatterns: ['\A#']

Metrics/AbcSize:
  Enabled: false
